import 'dart:io';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:path_provider/path_provider.dart';
import 'package:share_plus/share_plus.dart';

class PdfReportService {
  static Future<void> generateAndShareReport({
    required String patientName,
    required String age,
    required String Sex,
    required String mobileNumber,
    required Map<String, String> vitals,
    required Map<String, String> urineParameters,
    required String aiAnalysis,
    required String riskLevel,
    required String reportId,
  }) async {
    final pdf = pw.Document();
    final now = DateTime.now();
    
    // Professional Typography & Styles
    final titleStyle = pw.TextStyle(fontSize: 26, fontWeight: pw.FontWeight.bold, color: PdfColors.blue900);
    final subtitleStyle = pw.TextStyle(fontSize: 16, color: PdfColors.grey700);
    final headerStyle = pw.TextStyle(fontSize: 10, color: PdfColors.grey700);
    final sectionHeaderStyle = pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold, color: PdfColors.blue900);
    final contentStyle = pw.TextStyle(fontSize: 11);
    final riskStyle = pw.TextStyle(fontSize: 12, fontWeight: pw.FontWeight.bold, color: PdfColors.red700);
    final disclaimerStyle = pw.TextStyle(fontSize: 8, color: PdfColors.grey500);

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(32),
        header: (context) => pw.Column(
          children: [
            pw.Center(child: pw.Text('Health_Nexus', style: titleStyle)),
            pw.SizedBox(height: 4),
            pw.Center(child: pw.Text('AI Diagnostic Clinical Report', style: subtitleStyle)),
            pw.SizedBox(height: 15),
            pw.Row(
              mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
              children: [
                pw.Text('Report ID: $reportId', style: headerStyle),
                pw.Text('Date: ${now.day}/${now.month}/${now.year} ${now.hour}:${now.minute}', style: headerStyle),
              ],
            ),
            pw.SizedBox(height: 5),
            pw.Divider(thickness: 1, color: PdfColors.grey300),
            pw.SizedBox(height: 10),
          ],
        ),
        footer: (context) => pw.Column(
          children: [
            pw.Divider(color: PdfColors.grey300),
            pw.SizedBox(height: 4),
            pw.Row(
              mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
              children: [
                pw.Text('Generated by Health_Nexus PHC System', style: headerStyle),
                pw.Text('Page ${context.pageNumber} of ${context.pagesCount}', style: headerStyle),
              ],
            ),
            pw.SizedBox(height: 4),
            pw.Center(child: pw.Text('This report is system-generated and does not replace professional medical advice.', style: disclaimerStyle)),
          ],
        ),
        build: (context) => [
          pw.Text('Patient Information', style: sectionHeaderStyle),
          pw.SizedBox(height: 5),
          pw.Container(
            padding: const pw.EdgeInsets.all(8),
            decoration: pw.BoxDecoration(
              border: pw.Border.all(color: PdfColors.grey300),
              borderRadius: const pw.BorderRadius.all(pw.Radius.circular(4)),
            ),
            child: pw.Row(
              mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
              children: [
                pw.Column(crossAxisAlignment: pw.CrossAxisAlignment.start, children: [
                  pw.Text('Name: $patientName', style: contentStyle),
                  pw.SizedBox(height: 2),
                  pw.Text('Age: $age', style: contentStyle),
                ]),
                pw.Column(crossAxisAlignment: pw.CrossAxisAlignment.start, children: [
                  pw.Text('Sex: $Sex', style: contentStyle),
                  pw.SizedBox(height: 2),
                  pw.Text('Mobile: $mobileNumber', style: contentStyle),
                ]),
              ],
            ),
          ),
          pw.SizedBox(height: 20),

          pw.Text('Vital Parameters', style: sectionHeaderStyle),
          pw.SizedBox(height: 5),
          pw.Table.fromTextArray(
            headers: ['Parameter', 'Value'],
            data: vitals.entries.map((e) => [e.key, e.value]).toList(),
            headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold, color: PdfColors.white),
            headerDecoration: pw.BoxDecoration(color: PdfColors.blue700),
            cellStyle: contentStyle,
            cellAlignment: pw.Alignment.centerLeft,
            border: pw.TableBorder.all(color: PdfColors.grey300),
            cellPadding: const pw.EdgeInsets.all(5),
          ),
          pw.SizedBox(height: 20),

          if (urineParameters.isNotEmpty) ...[
            pw.Text('Urine Test Results', style: sectionHeaderStyle),
            pw.SizedBox(height: 5),
            pw.Table.fromTextArray(
              headers: ['Parameter', 'Result'],
              data: urineParameters.entries.map((e) => [e.key, e.value]).toList(),
              headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold, color: PdfColors.white),
              headerDecoration: pw.BoxDecoration(color: PdfColors.green700),
              cellStyle: contentStyle,
              cellAlignment: pw.Alignment.centerLeft,
              border: pw.TableBorder.all(color: PdfColors.grey300),
              cellPadding: const pw.EdgeInsets.all(5),
            ),
            pw.SizedBox(height: 20),
          ],

          pw.Text('AI Clinical Interpretation', style: sectionHeaderStyle),
          pw.SizedBox(height: 5),
          pw.Container(
            width: double.infinity,
            padding: const pw.EdgeInsets.all(10),
            decoration: pw.BoxDecoration(
              color: PdfColors.grey100,
              borderRadius: const pw.BorderRadius.all(pw.Radius.circular(4)),
              border: pw.Border.all(color: PdfColors.grey300),
            ),
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Text(aiAnalysis, style: contentStyle),
                pw.SizedBox(height: 10),
                pw.Divider(color: PdfColors.grey400),
                pw.SizedBox(height: 5),
                pw.Row(
                  children: [
                    pw.Text('Risk Level: ', style: pw.TextStyle(fontSize: 12, fontWeight: pw.FontWeight.bold)),
                    pw.Text(riskLevel, style: riskStyle),
                  ],
                ),
              ],
            ),
          ),
        ],
      ),
    );

    final output = await getTemporaryDirectory();
    final fileName = 'Health_Nexus_Report_${DateTime.now().millisecondsSinceEpoch}.pdf';
    final file = File('${output.path}/$fileName');
    await file.writeAsBytes(await pdf.save());

    await Share.shareXFiles(
      [XFile(file.path)],
      text: 'AI Diagnostic Clinical Report for $patientName',
    );
  }

  Future<File> generateReport({
    required String patientName,
    required String patientAge,
    required String patientSex,
    required DateTime timestamp,
    required Map<String, dynamic> vitalsData,
    required Map<String, dynamic> urineData,
    required String diagnosis,
    required String severity,
    required bool isEcgPerformed,
  }) async {
    final pdf = pw.Document();
    
    final titleStyle = pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold, color: PdfColors.blueGrey800);
    final headerStyle = pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold, color: PdfColors.blueGrey700);
    
    // A more professional row style with bold title and normal value
    pw.Widget buildInfoRow(String title, String value) {
      return pw.Padding(
        padding: const pw.EdgeInsets.symmetric(vertical: 4),
        child: pw.Row(
          mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
          children: [
            pw.Text(title, style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
            pw.Text(value, style: pw.TextStyle(fontWeight: pw.FontWeight.normal)),
          ],
        ),
      );
    }

    // Create a curated list of vital widgets to prevent printing raw data
    final List<pw.Widget> vitalWidgets = [];
    if (vitalsData['Heart Rate'] != null) {
      vitalWidgets.add(buildInfoRow('Heart Rate:', vitalsData['Heart Rate'].toString()));
    }
    if (vitalsData['SpO2'] != null) {
      vitalWidgets.add(buildInfoRow('SpO2:', vitalsData['SpO2'].toString()));
    }
    if (vitalsData['Body Temperature'] != null) {
      vitalWidgets.add(buildInfoRow('Body Temperature:', vitalsData['Body Temperature'].toString()));
    }
    
    vitalWidgets.add(buildInfoRow('ECG Status:', isEcgPerformed ? 'Performed' : 'Not Performed'));

    if (isEcgPerformed && vitalsData['Rhythm Pattern'] != null) {
      vitalWidgets.add(buildInfoRow('Rhythm Pattern:', vitalsData['Rhythm Pattern'].toString()));
    }

    // Create a formatted list of urine widgets
    final List<pw.Widget> urineWidgets = [];
    if (urineData.isNotEmpty && !(urineData.values.first.toString().contains('Not Analyzed'))) {
      urineData.forEach((key, value) {
        // Format keys like 'urine_glucose' to 'Urine Glucose'
        final formattedKey = key.replaceAll('_', ' ').split(' ').map((w) => w[0].toUpperCase() + w.substring(1)).join(' ');
        urineWidgets.add(buildInfoRow('$formattedKey:', value.toString()));
      });
    }
    
    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(30),
        build: (pw.Context context) => [
          pw.Header(
            level: 0,
            child: pw.Text('Health Nexus Diagnostic Report', style: titleStyle),
          ),
          pw.SizedBox(height: 20),
          
          pw.Text('Patient Details', style: headerStyle),
          pw.Divider(),
          buildInfoRow('Patient Name:', patientName),
          buildInfoRow('Age:', patientAge),
          buildInfoRow('Sex:', patientSex),
          buildInfoRow('Date:', timestamp.toLocal().toString().split(' ')[0]),
          pw.SizedBox(height: 20),
          
          pw.Text('Vitals & Diagnostics', style: headerStyle),
          pw.Divider(),
          ...vitalWidgets, // Use the curated list of vitals
          pw.SizedBox(height: 20),
          
          if (urineWidgets.isNotEmpty) ...[
            pw.Text('Urine Analysis', style: headerStyle),
            pw.Divider(),
            ...urineWidgets, // Use the curated list of urine results
            pw.SizedBox(height: 20),
          ],
          
          pw.Text('AI-Powered Analysis', style: headerStyle),
          pw.Divider(),
          pw.Container(
            padding: const pw.EdgeInsets.all(10),
            decoration: pw.BoxDecoration(
              color: PdfColors.grey100,
              borderRadius: pw.BorderRadius.circular(5),
            ),
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Text('Provisional Diagnosis:', style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
                pw.Text(diagnosis),
                pw.SizedBox(height: 10),
                pw.Text('Risk Level:', style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
                pw.Text(severity, style: pw.TextStyle(color: severity == 'High' ? PdfColors.red : (severity == 'Moderate' ? PdfColors.orange : PdfColors.green))),
              ],
            ),
          ),
        ],
      ),
    );

    final output = await getTemporaryDirectory();
    final file = File('${output.path}/Health_Report_${patientName.replaceAll(' ', '_')}.pdf');
    await file.writeAsBytes(await pdf.save());
    return file;
  }
}