// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHu-za7eQvbpJSZiBoKeEqRpIkzwf1xB8',
    appId: '1:300186178880:web:6acc2d50e5bfcf7f3ed6a5',
    messagingSenderId: '300186178880',
    projectId: 'healthnexus-3db2e',
    authDomain: 'healthnexus-3db2e.firebaseapp.com',
    storageBucket: 'healthnexus-3db2e.firebasestorage.app',
    measurementId: 'G-6QCXFM6YEH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWdyx4iwayJcY2F54NMEjl7PNazM5n6Oo',
    appId: '1:300186178880:android:ceadaa36800c71b13ed6a5',
    messagingSenderId: '300186178880',
    projectId: 'healthnexus-3db2e',
    storageBucket: 'healthnexus-3db2e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhdqbrSXU8erQ6t74IKTRdlWMEK58qUn0',
    appId: '1:300186178880:ios:3b55e6f01e0a9d2f3ed6a5',
    messagingSenderId: '300186178880',
    projectId: 'healthnexus-3db2e',
    storageBucket: 'healthnexus-3db2e.firebasestorage.app',
    iosBundleId: 'com.example.healthNexus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhdqbrSXU8erQ6t74IKTRdlWMEK58qUn0',
    appId: '1:300186178880:ios:3b55e6f01e0a9d2f3ed6a5',
    messagingSenderId: '300186178880',
    projectId: 'healthnexus-3db2e',
    storageBucket: 'healthnexus-3db2e.firebasestorage.app',
    iosBundleId: 'com.example.healthNexus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHu-za7eQvbpJSZiBoKeEqRpIkzwf1xB8',
    appId: '1:300186178880:web:466e30f379597a563ed6a5',
    messagingSenderId: '300186178880',
    projectId: 'healthnexus-3db2e',
    authDomain: 'healthnexus-3db2e.firebaseapp.com',
    storageBucket: 'healthnexus-3db2e.firebasestorage.app',
    measurementId: 'G-P7V4YNGNZH',
  );
}
